[project]
name = "BERT_Finetuning"
version = "0.1.0"
description = "Default template for PDM package"
authors = [
    {name = "zhangli", email = "2693175110@qq.com"},
]
dependencies = ["transformers==4.43.0", "scikit-learn>=1.7.2", "pandas>=2.3.3", "numpy==1.24.3", "tqdm>=4.67.1", "openpyxl>=3.1.5"]
requires-python = "==3.10.*"
readme = "README.md"
license = {text = "MIT"}


[tool.pdm]
distribution = false

[tool.ruff]
respect-gitignore = true

target-version = "py310"
line-length = 120
src = ["src"]

[tool.ruff.format]
quote-style = "single"

[tool.ruff.lint]
extend-select = [
  "I",    # isort
  "B",    # flake8-bugbear
  "C4",   # flake8-comprehensions
  "FA",   # flake8-future-annotations
  "PGH",  # pygrep-hooks
  "RUF",  # ruff
  "W",    # pycodestyle
  "UP",   # pyupgrade
  "YTT",  # flake8-2020
]
extend-ignore = ["B018", "B019", "RUF018"]
[dependency-groups]
dev = [
    "ruff>=0.14.7",
]
